// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: fraud_worker.proto

package workerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceWorker_Score_FullMethodName = "/fraud.worker.v1.InferenceWorker/Score"
)

// InferenceWorkerClient is the client API for InferenceWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceWorkerClient interface {
	Score(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
}

type inferenceWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceWorkerClient(cc grpc.ClientConnInterface) InferenceWorkerClient {
	return &inferenceWorkerClient{cc}
}

func (c *inferenceWorkerClient) Score(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, InferenceWorker_Score_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceWorkerServer is the server API for InferenceWorker service.
// All implementations must embed UnimplementedInferenceWorkerServer
// for forward compatibility.
type InferenceWorkerServer interface {
	Score(context.Context, *ScoreRequest) (*ScoreResponse, error)
	mustEmbedUnimplementedInferenceWorkerServer()
}

// UnimplementedInferenceWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceWorkerServer struct{}

func (UnimplementedInferenceWorkerServer) Score(context.Context, *ScoreRequest) (*ScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Score not implemented")
}
func (UnimplementedInferenceWorkerServer) mustEmbedUnimplementedInferenceWorkerServer() {}
func (UnimplementedInferenceWorkerServer) testEmbeddedByValue()                         {}

// UnsafeInferenceWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceWorkerServer will
// result in compilation errors.
type UnsafeInferenceWorkerServer interface {
	mustEmbedUnimplementedInferenceWorkerServer()
}

func RegisterInferenceWorkerServer(s grpc.ServiceRegistrar, srv InferenceWorkerServer) {
	// If the following call pancis, it indicates UnimplementedInferenceWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceWorker_ServiceDesc, srv)
}

func _InferenceWorker_Score_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceWorkerServer).Score(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceWorker_Score_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceWorkerServer).Score(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferenceWorker_ServiceDesc is the grpc.ServiceDesc for InferenceWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fraud.worker.v1.InferenceWorker",
	HandlerType: (*InferenceWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Score",
			Handler:    _InferenceWorker_Score_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fraud_worker.proto",
}
